modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="toastcontrol"

version="10.0.0-beta0"

displayName="Toast Control"

authors="Shadows_of_Fire"

description='''Blocking annoying popups since 1.12'''



[[dependencies.toastcontrol]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toastcontrol]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.64-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toastcontrol]]
    modId="placebo"
    type="required"
    versionRange="[10.0.1,)"
    ordering="NONE"
    side="BOTH"
